included:
  - WeatherApp


disabled_rules:
  - colon
  - conditional_returns_on_newline
  - convenience_type
  - cyclomatic_complexity
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - function_default_parameter_at_end
  - implicitly_unwrapped_optional
  - legacy_multiple
  - missing_docs
  - multiline_arguments_brackets
  - multiline_parameters_brackets
  - nesting
  - no_extension_access_modifier
  - no_grouping_extension
  - nslocalizedstring_require_bundle
  - object_literal
  - prefixed_toplevel_constant
  - private_action
  - prohibited_interface_builder
  - prohibited_super_call
  - reduce_into
  - required_deinit
  - sorted_imports
  - strict_fileprivate
  - strong_iboutlet
  - todo
  - trailing_whitespace
  - type_contents_order
  - unavailable_function
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - file_types_order

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - contains_over_first_not_nil
  - control_statement
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_object_literal
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_length
  - first_where
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - implicit_return
  - inert_defer
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_random
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - no_fallthrough_only
  - notification_center_detachment
  - nslocalizedstring_key
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - protocol_property_accessors_order
  - reduce_boolean
  - redundant_discardable_let
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - return_arrow_whitespace
  - required_enum_case
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - statement_position
  - static_operator
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - toggle_bool
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - type_body_length
  - type_name
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
  - weak_delegate
  - xctfail_message
  - yoda_condition

function_body_length:
  warning: 25
  error: 40

function_parameter_count:
  warning: 5
  error: 6

identifier_name:
  min_length:
    error: 2
    warning: 2
  max_length:
    error: 50
    warning: 50
  excluded:
    - i
    - k
    - x
    - y

line_length:
  warning: 145
  error: 150

modifier_order:
  preferred_modifier_order:
    - acl
    - override
    - setterACL
    - dynamic
    - mutators
    - lazy
    - final
    - convenience
    - required
    - typeMethods
    - owned

type_body_length:
  warning: 200
  error: 350

type_name:
  max_length:
    warning: 50
  excluded:
    - ID

custom_rules:
  empty_line_after_guard:
    name: Empty Line After Guard
    regex: |-
      ^ *guard[ a-zA-Z0-9=?.\(\),><!]*\{[ a-zA-Z0-9=?.\(\),><!]*\}
       *(?!(?:return|guard))\S+
    message: There should be an empty line after a guard
    severity: warning
  newline_after_opening_braces:
    included: ".*.swift"
    name: Newline after Opening Braces
    regex: "^ *(public|internal|private|fileprivate|open)? *(final)? *(class|extension)
      [a-zA-Z:><.,_=1-9 ]+ \\{ *\\n(\\t|\\f| )*\\S"
    message: Include newline after opening brace
    severity: warning
  newline_before_closing_braces:
    included: ".*.swift"
    name: Newline before Closing Braces
    regex: |-
      ^(\t|\f| )*\}
      \}
    message: Include newline before closing brace
    severity: warning
  standard_user_defaults:
     included: ".*.swift"
     excluded: ".*UserDefaultsExtensions.swift"
     name: Forbidden use of standard user defaults
     message: Please, use UserDefaults.vivid instead of UserDefauls.standard
     regex: |-
       ^ *UserDefaults.standard
     severity: error
